### ISSUE TITLE
reading input from csv for a subject

### ISSUE THREAD

**Issue by 99003554** [amanajaykalaskar/Mark_Analysis#3]
Anomalous backslash in string: '\C'. String constant might be missing an r prefix.
	"startLineNumber": 60,
	"endLineNumber": 60,

**Comment by 99003521** [comment]
Thanks Ragul for noticing the error. The issue is fixed now.

**Comment by 99003521** [comment]
Thanks Ragul for noticing the error. The issue is fixed now.
